version: '3.8'
services:
  app:
    build:
      context: ..\backend
      dockerfile: ..\docker\Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/wallet
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:
